### ISSUE TITLE
Minimum password strength for user accounts

### ISSUE THREAD

**Issue by redshiftzero** [flexyourrights/openpolice#1]
Potential complainants can currently create accounts with very weak passwords, it would be good to have some password complexity measure, e.g. using [zxcvbn](https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/)

**Comment by wikiworldorder** [comment]
Thanks so much for kicking off our tech feedback! This week, I am getting the OPC code base fully caught up with the past three months of SurvLoop upgrades. I look forward to correcting these good issues you've brought up!

**Comment by wikiworldorder** [comment]
I LOVE the zxcvbn solution to the password strength issue, and think it's a great upgrade to the more general SurvLoop system I've built for OpenPolice.org. Thank you redshiftzero!! <3
